mongo:
  url: mongodb://root:123@8.134.53.178:27017/?authSource=admin
  username: root
  password: 123
  database: fastChat

server:
  http:
    addr: ':8080'
  websocket:
    addr: ':8000'
    pattern: '/ws'